version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=bank
    volumes:
      - bank_db_volume:/var/lib/postgresql/data

  fps:
    image: fps
    container_name: fps
    build:
      dockerfile: ../Dockerfile
      context: ../
    ports:
      - "8080:8080"

volumes:
  bank_db_volume: